CREATE TABLE Recipes (
	Id INTEGER PRIMARY KEY, 
	Title TEXT NOT NULL,
	AuthorId INTEGER NULL,
	SiteId INTEGER NOT NULL,
	Url TEXT NOT NULL,
	ImageUrl TEXT NULL,
	IncludeInSearches INTEGER NOT NULL
);


CREATE TABLE Sites (
	Id INTEGER PRIMARY KEY,
	Name TEXT NOT NULL,
	Url TEXT NOT NULL,
	EnableScraping INTEGER NOT NULL,
	LastModified TEXT NOT NULL
);