CREATE TABLE Cuisines(
	Id INTEGER PRIMARY KEY,
	[Name] TEXT NOT NULL,
	Generic INTEGER NOT NULL,
	Esque INTEGER NOT NULL
);

CREATE TABLE Recipes (
	Id INTEGER PRIMARY KEY,
	Title TEXT NOT NULL,
	AuthorId INTEGER NULL,
	SiteId INTEGER NOT NULL,
	Url TEXT NOT NULL,
	ImageUrl TEXT NULL,
	IncludeInSearches INTEGER NOT NULL
);

CREATE TABLE RecipeIngredients(
	Id INTEGER PRIMARY KEY,
	TextId INTEGER NOT NULL,
	ComponentId INTEGER NOT NULL,
	MultipleChoice INTEGER NOT NULL
);

CREATE TABLE IngredientText(
	Id INTEGER PRIMARY KEY,
	RecipeId INTEGER NOT NULL,
	[TEXT] TEXT NOT NULL
);